// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWOEZZGEnB1Boe_d8ugnt-UW7J5J3yW0',
    appId: '1:1072231117405:web:b14c700acf9cadebf213b4',
    messagingSenderId: '1072231117405',
    projectId: 'translator-app-84872',
    authDomain: 'translator-app-84872.firebaseapp.com',
    storageBucket: 'translator-app-84872.firebasestorage.app',
    measurementId: 'G-L5VHYZKGB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGaRMV0fPq6pjgg6PVBAzd-p3fhNPnyI',
    appId: '1:1072231117405:android:0f6d0c2cf5ae392bf213b4',
    messagingSenderId: '1072231117405',
    projectId: 'translator-app-84872',
    storageBucket: 'translator-app-84872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7hThoMY2msVJpkM1BZPVMJ8dU0F9MMU',
    appId: '1:1072231117405:ios:b2b2820395478396f213b4',
    messagingSenderId: '1072231117405',
    projectId: 'translator-app-84872',
    storageBucket: 'translator-app-84872.firebasestorage.app',
    iosClientId: '1072231117405-ed27fmsfgcs6v35a7mvueefi8bha6vdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.translatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7hThoMY2msVJpkM1BZPVMJ8dU0F9MMU',
    appId: '1:1072231117405:ios:b2b2820395478396f213b4',
    messagingSenderId: '1072231117405',
    projectId: 'translator-app-84872',
    storageBucket: 'translator-app-84872.firebasestorage.app',
    iosClientId: '1072231117405-ed27fmsfgcs6v35a7mvueefi8bha6vdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.translatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWOEZZGEnB1Boe_d8ugnt-UW7J5J3yW0',
    appId: '1:1072231117405:web:7f8aa28dc8156e7ef213b4',
    messagingSenderId: '1072231117405',
    projectId: 'translator-app-84872',
    authDomain: 'translator-app-84872.firebaseapp.com',
    storageBucket: 'translator-app-84872.firebasestorage.app',
    measurementId: 'G-K2ND7KDGF8',
  );
}
